### ISSUE TITLE
Read-Only and Editable Modes for Getting Started

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#12]
We want to use the Getting Started page in two contexts:
- On a Prominic server, where staff will write the articles in the application (to hopefully make the formatting more consistent)
- On the Super.Human.Installer servers, where the user will want to read the articles but doesn't need to edit them.

The mode will be configured by a flag in the configuration agent that will be added for #1.  I'll give more details when this is ready.

**Comment by piotrzarzycki21** [comment]
I have made on UI sight small preparations for read only mode. Everything is on the branch related to #10

**Comment by JoelProminic** [comment]
The configuration flag is now available in the [ConfigRead](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/1#issuecomment-1412452473) agent.  Enable edit mode if `ui_documentation_editable` is `true`, and disable it otherwise.

**Comment by piotrzarzycki21** [comment]
This has been applied and it's ready for tests.

**Comment by JoelProminic** [comment]
I see that if I set ui_documentation_editable=true, the additional buttons are not displayed when I first open the interface:
![image](https://user-images.githubusercontent.com/24532731/217317948-2a204ef3-5828-4c49-9612-fd3d19d66881.png)

But they do display after opening a document an clicking Back:
![image](https://user-images.githubusercontent.com/24532731/217318215-23d11c39-5b6c-4c32-a5e3-1881771c15c7.png)

**Comment by piotrzarzycki21** [comment]
> I see that if I set ui_documentation_editable=true, the additional buttons are not displayed when I first open the interface: ![image](https://user-images.githubusercontent.com/24532731/217317948-2a204ef3-5828-4c49-9612-fd3d19d66881.png)
> 
> But they do display after opening a document an clicking Back: ![image](https://user-images.githubusercontent.com/24532731/217318215-23d11c39-5b6c-4c32-a5e3-1881771c15c7.png)

@JoelProminic This has been fixed.

**Comment by piotrzarzycki21** [comment]
I'm closing it. If you find some issue please open it.
