### ISSUE TITLE
Display Access Information About Installed Genesis Applications

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#13]
As discussed with @JustinProminic, we would like to display access information in the interface for applications installed from Genesis.  This can include:
- An HTML-formatted explanation of how to use the application
- Links to local pages associated with the application
- Links to local database, which will open with the `Notes://` protocol and/or go through Nomad.

The proposed JSON format will be something like this:
```
      "apps": [
        {
          "installed": false,
          "access": {
            "description": "Placeholder description.",
            "links": [
              {
                "name": "Example Link",
                "type": "browser",
                "url": "/auth.nsf/XMLAuthenticationTest?OpenAgent"
              }
            ]
          },
          "AppID": "javaaddindemo",
          "DetailsURL": "https://genesis.directory/apps/javaaddindemo",
          "Label": "JavaAddin - Demo",
          "InstallCommand": "install javaaddindemo"
        },

```

I'll add more details as I continue working on this.

**Comment by JoelProminic** [comment]
I made a quick mockup to clarify what we want here:
![image](https://user-images.githubusercontent.com/24532731/217329454-c1870e42-d69c-4c24-90a5-7f73fb5c1f14.png)

Note that we may have another type called `database` which will open the database with:
- NomadWeb
- The local notes client, using notes://

I'm hoping I can simplify this down to just a `url` property so that the functionality is the same between the `browser` and `database` types.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, @JustinProminic would like to get some implementation of this interface working before the demo.   The components are:
- @dpastov will add links in the app JSON
- I will update the agent to return links in the format I described above
- The Royale interface will need to be updated to show the sidebar entries dynamically for applications with installed=true.  If you need to simplify this interface for the initial version, that is fine.

I'll plan to get you an agent with some placeholder configuration for this by the end of the day so that you can start testing.  I thought we had done this earlier, but I didn't see any test agents linked.

**Comment by JoelProminic** [comment]
@piotrzarzycki21,  I added an example entry called "Xample Addin" (I wanted it to appear at the end of the list so that it would be less obvious if we forget to remove it).  The configuration looks like this:

```
    {
      "access": {
        "description": "This is not a real application.  It is being used for testing only, and will be removed at a later time.",
        "links": [
          {
            "name": "Example Link",
            "type": "browser",
            "url": "/SuperHumanPortal.nsf/XMLAuthenticationTest?OpenAgent"
          },
          {
            "name": "Example Database",
            "type": "database",
            "url": "notes://demo.startcloud.com/SuperHumanPortal.nsf"
          }
        ]
      },
      "AppID": "xampleaddin",
      "DetailsURL": "https://genesis.directory/apps/superhumanportal",
      "Installed": true,
      "Label": "Xample Addin",
      "InstallCommand": "install superhumanportal"
    }
```

You will need to import the agents with Project > Run on Vagrant to get the changes.

Note that the second link uses the `notes://` protocol.  Unfortunately, this will only work with the default server name - as a future task we will need to find a way to insert the local server.

I remember that I had brainstormed other link types with @JustinProminic and @dpastov, but I haven't found my notes for this.  This should be enough to experiment with the interface updates, though.

**Comment by JoelProminic** [comment]
@dpastov, I updated the agent to copy the `access` node if it is found in the Genesis API data.   If we need to change the format, that is fine at this point.

To make these links portable, I would select a couple conventions.
- If you need to open databases or other applications in a browser, use relative links (i.e. `/SuperHumanPortal.nsf/XMLAuthenticationTest?OpenAgent`)
- If you need to reference the Domino server name, use the `%SERVER_ABBR%` value for the abbreviated name, and `%SERVER_COMMON%` for the common name.  I can update my agent to insert the abbreviated server name.   Let me know if you need more insertion parameters.

**Comment by piotrzarzycki21** [comment]
Update:
- I have implemented so far population of menu with installed applications. You can check that on branch. I'm progressing farther with UI when user click on installed app. 

https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/4754037736

**Comment by JoelProminic** [comment]
@piotrzarzycki21, this is looking good so far:
![image](https://user-images.githubusercontent.com/24532731/233443415-b3379c8a-ed6d-49d0-991a-96d6d9e6abd5.png)

I tried:
1. Load the application.  The Installed Apps are populated
2. Install an app. This does not update Installed Apps automatically, but the install is not finished at this point. 
3. Hit the Refresh button in Genesis Apps.  Installed Apps is updated.   With the current logic, I would expect the installed application to be available almost immediately.

**Comment by JoelProminic** [comment]
The update looks like this.  I see the buttons are still pending:
![image](https://user-images.githubusercontent.com/24532731/233485349-558b4dc4-c985-455c-a560-32e4a8e7ed35.png)

Note that the App Details link give a 404 for Xample Addin.  I see this was a problem with the original URL (from the Super.Human.Portal addin).  The link does work properly for DBSigner:

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed version with links. I have decided merge as well everything to master as squashed commit. If for some reason we would like to get back to previous version it will be easy revert that one commit.
Here is how it looks like:
<img width="1792" alt="Screenshot 2023-04-21 at 13 44 03" src="https://user-images.githubusercontent.com/24554795/233627894-f0650d69-a720-417b-9442-c9aeb0b4c22b.png">

Release:
- If you decide make another pre-release you should push tag v0.1.4. Action create for you Draft of release which has to be published manually. Instruction for making release is [here](https://github.com/Moonshine-IDE/Super.Human.Portal/wiki/Super.Human.Portal-GitHub-Release-Instructions).
- In my opinion if portal has to be released in a production state you should change in pom.xml file version to [v1.1.0](https://github.com/Moonshine-IDE/Super.Human.Portal/milestone/2) and update CHANGELOG. After that go trough relase process.

I should be available till 1PM your time today, but later on next I will check stuff in 6h or so. 

Side note: We were checking Super Human Portal deployed so far in Super Human Installer and it looks like agents do not return what is installed. Maybe they there are old version of these agents there ?

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I confirmed you update is working.  

![image](https://user-images.githubusercontent.com/24532731/233697639-df60f240-9671-4e7a-86ad-e003bfbbedf0.png)

@dpastov added this link for the "Absence Mail" addin.  Note that this is type=database, but we'll add new logic for this in a separate issue.  For now, I'll clean up this on the agent side so that it will work like a browser link.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, if the Installed flag is not working, then try updating my agents for [this change](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/10#issuecomment-1515505643).

I'll planning to make some quick changes for the type=database case, so watch for that.  These updates will be included in my next database update for the Genesis superhumanportal addin.

**Comment by piotrzarzycki21** [comment]
Joel but this was not my local problem with demo-1.1 vagrant, but problem with what was run from Super Human Installer. Trough demo-1.1 everything is working.

**Comment by JoelProminic** [comment]
Hmm, this is working properly for me with Super.Human.Installer.  Note that you'll need to change gradle.properties to match your created server name.  Maybe I should update the server to "" and rely on us using Project > Run on Vagrant for test deployment...

**Comment by JoelProminic** [comment]
Anyway, this is working as expected for browser links.   I'll create a separate issue for database links.   I'm going to push 0.1.4 in a bit.
