### ISSUE TITLE
Version of Super.Human.Portal is not visible

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#20]

**Comment by JoelProminic** [comment]
I can see "Version 0.1.5-SNAPSHOT" in the bottom-right when testing the [latest dev build](https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/4829376163).  Was this fixed, or does this mean it is an intermittent problem.

**Comment by piotrzarzycki21** [comment]
I think this is something with cache that I have this issue. It is working fine in my opinion.

**Comment by JoelProminic** [comment]
Once I created the release for Super.Human.Portal v0.1.5, I found that the version number is not displayed in the release build:

![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/86f1aa29-4598-4ffc-814c-c1aeb6ace3bb)

I do see it in the last debug/development build, though.

**Comment by piotrzarzycki21** [comment]
I can reproduce issue with 0.1.5 in my local server - I will investigate probably after vacation.

**Comment by piotrzarzycki21** [comment]
@JoelProminic this can be tested one we deploy release version of application so I'm closing this issue.

**Comment by JoelProminic** [comment]
I confirmed this on the 0.1.7 release.  The contrast is a bit low, maybe, but this should give us what we need:
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/6fb05103-a6a7-4d53-9ee3-d687ffef138b)
