### ISSUE TITLE
Display application in installed list after click on "Install"

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#21]
Once user click install server need a bit of time before application gets installed. We would like to make small delay after installation and try to refresh list of installed app.

**Comment by piotrzarzycki21** [comment]
This should work fine, but I have raised another issue which is separated, but discovered as part of work on this one #23

**Comment by JoelProminic** [comment]
Currently, this reloads the application list after about 1 second.  This works because the Vagrant server is not busy, and the agent only checks if the addin directory was created.  However:
- This may be too fast if we are running this on a busy production server in the future
- The application may not be fully installed at this point, so the links won't necessarily work.

@JustinProminic requested that we update the logic to display a messsage like "Installing:  15 seconds remaining..." and then count down the timer before refreshing the page.  This should be plenty of time for the current applications to be installed.

Some ideas:
- We could offer a way to close the countdown so that that the user can do something else.  However, this means that the refresh could trigger in the middle of something else, so this will probably cause more annoyance than it is worth.
- It could be nice to configure this per-application as a `installTime` property.  This could be defaulted on the agent side, or based on a configuration value.  This would also let us add the `installTime` later in Genesis, without updating the UI.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I will improve that early next week, if there is any urgency to release 0.1.5 move it to the next milestone please.

**Comment by JoelProminic** [comment]
I added the `InstallTimeS` property for each application, which indicates the time in seconds for the install delay.  For now, this is hard-coded to 15 seconds, but I plan to make it configurable later.  Sorry, I meant to get this released to you sooner.

**Comment by JoelProminic** [comment]
We reviewed this today, and it looks mostly good.  Some tweaks we discussed:
- Determine wait time dynamically.  See `InstallTimeS` above.
- Display a countdown for the install - this something we discussed originally.
- The message is not centered on the loading icon currently.
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/3e8410b6-e3b0-4f5e-a6a2-75296ccb7723)

**Comment by JoelProminic** [comment]
I added a configuration value for InstallTimeS:  `default_install_time_s`

`default_install_time_s` | InstallTimeS
-- | --
Not set | 15
Set to `10` | 10
Set to `-1` | 15


I deployed the last builds of the Royale application from here:  https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/4959806131

However, I don't see the countdown or the loading icon at this point.  Instead, I see a snackbar, and the GenesisRead data is not reloaded.

**Comment by piotrzarzycki21** [comment]
I think there is something wrong with build. All of the symptoms indicates for an old build. Did you try to check in Incognito Tab?

**Comment by JoelProminic** [comment]
I agree that it seems strange.   However, I ran the application in private browsing mode, and did some other tests to confirm I was on the correct server.  I also tried uploading another build from my last update.    I'll let you know if I find more clues for this.

**Comment by piotrzarzycki21** [comment]
@JoelProminic let's check this than in a different way. Go to development tools Source code tab. Find file called `SuperHumanPortal_Royale.js` - search function `getCurrentDelayTimeInSeconds` - If exists this is the freshest code, if not you have still something old.

**Comment by JoelProminic** [comment]
Sorry, it seems this was some sort of caching issue on my side.  I'm not sure what I missed...

When I revisited this today, I confirmed I could see this message:

![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/08ebc275-7a24-4e44-a84d-cf87dd4f3d3b)

Note that the message is still off-center with the icon.  I think we also need some tweaks to the message.  We can discuss this more in the meeting tomorrow but I would suggest

> Installation is in progress.  X seconds remaining.

"seconds" should be "second" if there is only 1 second remaining.

Alternatively, we could display the number as a countdown as part of the loading icon or a progress bar.

**Comment by piotrzarzycki21** [comment]
> Sorry, it seems this was some sort of caching issue on my side. I'm not sure what I missed...
> 
> When I revisited this today, I confirmed I could see this message:
> 
> ![image](https://user-images.githubusercontent.com/24532731/238454475-08ebc275-7a24-4e44-a84d-cf87dd4f3d3b.png)
> 
> Note that the message is still off-center with the icon. I think we also need some tweaks to the message. We can discuss this more in the meeting tomorrow but I would suggest
> 
> > Installation is in progress.  X seconds remaining.
> 
> "seconds" should be "second" if there is only 1 second remaining.
> 
> Alternatively, we could display the number as a countdown as part of the loading icon or a progress bar.

I have adjusted message and position of message on screen. Latest build should have all changes.

**Comment by JoelProminic** [comment]
The update looks good.  We'll discuss it more in the meeting.
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/65479a37-de60-4ecd-b3c2-a1c3159ac1af)

**Comment by JoelProminic** [comment]
We reviewed this in the meeting, and it should be sufficient for now.
