### ISSUE TITLE
Duplicate Fields for New Documentation Document

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#25]
I see duplicate fields when I click Add in the Getting Started interface.  This does not trigger if I edit an existing document before creating a new document:
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/9af07547-f645-4318-ac3b-e2fbc19cc880)

**Comment by piotrzarzycki21** [comment]
Issue has been fixed. Ready for tests.

**Comment by JoelProminic** [comment]
This was fixed for the Edit button, but not for the Add button.  Note that this only triggers if you open Add before editing any document:
1. Refresh the page
2. Click Add
3. The fields are duplicated

**Comment by piotrzarzycki21** [comment]
> This was fixed for the Edit button, but not for the Add button.  Note that this only triggers if you open Add before editing any document:
> 
> 1. Refresh the page
> 
> 2. Click Add
> 
> 3. The fields are duplicated

This has been fixed with latest build.

**Comment by JoelProminic** [comment]
I confirmed that this is fix.  I also retested Edit for the first action, both by clicking the button and by double-clicking the row.
