### ISSUE TITLE
Miscellaneous fixes in the Getting Started Interface

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#26]
Some minor issues:
- Cut off row in search
- "Cancel" should be "Back" in read mode
- Header on documentation should be larger

**Comment by piotrzarzycki21** [comment]
I have fixed all issues listed here plus I have improved cutted DataGrid issue which we have seen in our last meeting.

**Comment by JoelProminic** [comment]
The original issues I reported have been fixed.  The datagrid height also resizes correctly now.

However, I see a new related issue.  If I search for "Notes", then I only see one document.  However, there is a scroll in the datagrid, and you can move it to see a second detected document.

Similarly, if I search for "Domino" I see multiple documents, but the last document is hidden by the scroll.

**Comment by piotrzarzycki21** [comment]
> The original issues I reported have been fixed. The datagrid height also resizes correctly now.
> 
> However, I see a new related issue. If I search for "Notes", then I only see one document. However, there is a scroll in the datagrid, and you can move it to see a second detected document.
> 
> Similarly, if I search for "Domino" I see multiple documents, but the last document is hidden by the scroll.

This issue has been fixed. I have improved general look and paddings in both views. Currently when you search DataGrid will almost not change it's sizes - all items which you will find should be nicely displayed.

**Comment by JoelProminic** [comment]
The datagrid resizing works great on the Getting Started page, but I see that the datagrid does not resize in Genesis App.  The pagination buttons are not visible unless my browser window is at least 900 px tall.  I'm testing on macOS Firefox.

**Comment by JoelProminic** [comment]
Nevermind, I found I was accidentally using an old js-release build :(

Switching to js-debug, I could not trigger these problems anymore.
