### ISSUE TITLE
"undefined" URL on Refresh

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#29]
@piotrzarzycki21 I have been seeing an error a lot recently where Super.Human.Portal does not open fully after refreshing the page.  Checking the debug console, I see a failed URL call to:  https://%server%/Super.Human.Portal/js-debug/undefined

The application seems to open properly the first time, and then I have trouble opening it again, even if I do a hard refresh (i.e. CMD-Shift-R) or open it in a private browsing window.  I have been primarily testing with macOS Firefox.

Do you have any ideas about what could cause this?  The called URLs are:
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/05cc3089-ee9b-4bb3-8b81-318ab9ee286d)

This has been especially bad on domino-49 - I sent an email with the URL if you have access.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed some changes which may fix this issue. Could you deploy new version to server mentioned in email. I could reproduce that issue on that server in Incognito Tab, but I cannot on my sight. We just need to test new build on that server.

**Comment by JoelProminic** [comment]
I updated js-debug on domino-49, and I haven't been able to reproduce the error.  I'll update the issue if I see this again later.

FYI, SuperHumanPortal.nsf has a different path on domino-49, so I had to update SuperHumanPortal_Royale.js manually to fix the base path.  If this was the cause, though, I would expect it to give me an error for a wrong path instead of `undefined`.

**Comment by piotrzarzycki21** [comment]
> I updated js-debug on domino-49, and I haven't been able to reproduce the error. I'll update the issue if I see this again later.
> 
> FYI, SuperHumanPortal.nsf has a different path on domino-49, so I had to update SuperHumanPortal_Royale.js manually to fix the base path. If this was the cause, though, I would expect it to give me an error for a wrong path instead of `undefined`.

I'm not sure if I understand. You have updated that path manually where ?

**Comment by JoelProminic** [comment]
After I unzipped the build on domino-49, I updated SuperHumanPortal.nsf to A55606/SuperHumanPortal.nsf in 6 locations in  SuperHumanPortal_Royale.js.  Even if I made a mistake on these updates last week, I wouldn't expect to see an undefined URL, but I mentioned this in case there was some reason that this would explain the difference between the servers.  You can see the old build if you switch to js-debug-undefined in the domino-49 URL>

**Comment by piotrzarzycki21** [comment]
> After I unzipped the build on domino-49, I updated SuperHumanPortal.nsf to A55606/SuperHumanPortal.nsf in 6 locations in SuperHumanPortal_Royale.js. Even if I made a mistake on these updates last week, I wouldn't expect to see an undefined URL, but I mentioned this in case there was some reason that this would explain the difference between the servers. You can see the old build if you switch to js-debug-undefined in the domino-49 URL>

This worries me a bit, because right now we are using release non minimized version of application. When we release we will have minimized version and you won't be able so easly update all of that. I think I need to provide some way of updates. We should talk about that tomorrow.

**Comment by JoelProminic** [comment]
I haven't seen this trigger again since the update.   I'll reopen/recreate it if I see the issue again.
