### ISSUE TITLE
Change Jodit Editor to different one

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#31]
We have two rich text editor which we consider to use:
- DevExpress [HTMLTextEditor](https://js.devexpress.com/Documentation/Guide/UI_Components/HtmlEditor/Getting_Started_with_HtmlEditor/) which is part of used library in our apps. Editor is based on [fork of Quill](https://github.com/DevExpress/devextreme-quill/) text editor. 
- [RichTextEditor](https://richtexteditor.com/demos/default.aspx)

**Comment by piotrzarzycki21** [comment]
@JoelProminic Editor has been change you can deploy last dev version and test -> https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/5345452277

**Comment by JoelProminic** [comment]
The build had expired, so I re-ran it:  https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/5345925763

**Comment by JoelProminic** [comment]
I deployed a test build here: 

https://domino-49.prominic.net/Super.Human.Portal/js-debug/index.html

Some features that do not seem to be working properly:
- Variable:  I don't see an option to change the value here
- "Font" (TT):  This toggles to one other font.  I feel like this is missing a drop-down to select font and/or size.

**Comment by piotrzarzycki21** [comment]
> I deployed a test build here:
> 
> https://domino-49.prominic.net/Super.Human.Portal/js-debug/index.html
> 
> Some features that do not seem to be working properly:
> 
> * Variable:  I don't see an option to change the value here
> * "Font" (TT):  This toggles to one other font.  I feel like this is missing a drop-down to select font and/or size.

@JoelProminic I have added FONT options. It turns out some items in toolbar have to have [acceptedValues set to appear](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/b9c23a4fb8010a63c94137e064fa91055209b4a7/Super.Human.Portal_Royale/src/generated/Super.Human.Portal_Royale/classes/htmlEditor/helpers/ToolbarItems.as#L9). The question is what FONT we would like to have there and what sizes ? 

Newest build have that update: https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/5410886851

**Comment by JoelProminic** [comment]
This update was sufficient for now, so we will publish a v0.1.16 release.

There is a remaining issue where special characters are added and do not display properly when copying text from another webpage (this seems to be related to links).  For now, we can clean this manually.
