### ISSUE TITLE
Cancel/Back Button Updates for DocumentationForm

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#34]
When a DocumentationForm document in Getting Started is open in read mode, the "Cancel" button shoudl be "Back".   In edit mode, it should remain as "Cancel".

TODO:  Should the button in edit mode return to read-only mode, or return to the article list (current behavior?  We can discuss this briefly tomorrow.

**Comment by piotrzarzycki21** [comment]
> When a DocumentationForm document in Getting Started is open in read mode, the "Cancel" button shoudl be "Back". In edit mode, it should remain as "Cancel".

I have pushed changes for that part. We can discuss over next meeting about behaviour of "Cancel"/"Back" button.

**Comment by JoelProminic** [comment]
I didn't test this update when pushing out v0.1.8.   I see this behavior currently:

ui_documentation_editable | Edit Mode | Expected Button Name | Actual
-- | -- | -- | --
false | No | Back | Confirmed
true | No | Back | BUG:  this is currently Cancel
true | Yes | Cancel | Confirmed

**Comment by piotrzarzycki21** [comment]
> 

Scenario has been applied.
