### ISSUE TITLE
Update Bookmarks to Prioritize "Open in Nomad" Action

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#46]
As we move towards using Super.Human.Portal as a customer portal, we we would like to focus on opening the bookmarks in Nomad.  Currently, the biggest button is to expand the database details, which is too much information for end users.  Instead we would like to have this open in Nomad, and then provide the database details and other actions with a smaller expand button.

I'd like to mockup something for this for the next meeting before we start working on it.

**Comment by JoelProminic** [comment]
Here is the updated mockup.  Let me know if you need more clarification:
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/e8425e11-1570-4be6-86d4-e12ff51c9381)

I will need to provide a configuration for this.   I'll try to get you something for this and #44 today or tomorrow.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes for Bookmarks. I have put edit/delete buttons in a different location - I feel like having them in the right spot would emphasis less Open in Nomad button. Newest build should have all my updates.

**Comment by JoelProminic** [comment]
We would also like to add an optional description property for the bookmarks, similar to what we have for Installed Applications.  This will need to be updated in the Royale form as well as the database and agents.  The current plan is to display the description to the right of the collapsed  bookmarks.

**Comment by piotrzarzycki21** [comment]
> We would also like to add an optional description property for the bookmarks, similar to what we have for Installed Applications. This will need to be updated in the Royale form as well as the database and agents. The current plan is to display the description to the right of the collapsed bookmarks.

@JoelProminic I have added description - when you add this to bookmark it will be displayed like that:

<img width="1791" alt="Screenshot 2023-11-15 at 11 57 05" src="https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24554795/28392592-3b13-4f32-9369-4708dc4e1e75">

**Comment by JoelProminic** [comment]
I added the `defaultAction` property.  The values are:

Value | Behavior
-- | --
nomad | Open with `nomadURL`.  Use this as the default if you get an unexpected value
notes | Open with `url` (Notes client)

This affected several agents:

Agent | Updated
-- | --
CustomBookmarkCreate (response) | Confirmed
CustomBookmarkRead (Bookmarks) | Confirmed
CustomBookmarkUpdate (response) | Confirmed
DatabaseRead  (Browse My Server) | Confirmed
GenesisInstall | Updated code is not directly used
GenesisRead (Installed Apps) | Confirmed

To test the "notes" value, create a new ConfigValue document in the Configuration view:  Key = `link_default_action`, Value = `notes`

**Comment by piotrzarzycki21** [comment]
> I added the `defaultAction` property. The values are:
> 
> Value	Behavior
> nomad	Open with `nomadURL`. Use this as the default if you get an unexpected value
> notes	Open with `url` (Notes client)
> This affected several agents:
> 
> Agent	Updated
> CustomBookmarkCreate (response)	Confirmed
> CustomBookmarkRead (Bookmarks)	Confirmed
> CustomBookmarkUpdate (response)	Confirmed
> DatabaseRead (Browse My Server)	Confirmed
> GenesisInstall	Updated code is not directly used
> GenesisRead (Installed Apps)	Confirmed
> To test the "notes" value, create a new ConfigValue document in the Configuration view: Key = `link_default_action`, Value = `notes`

This has been handled on UI sight.

**Comment by JoelProminic** [comment]
Agent | defaultAction=notes | defaultAction=nomad
-- | -- | --
CustomBookmarkCreate (response) | N/A | N/A (CustomBookmarkRead is called first)
CustomBookmarkRead (Bookmarks) |  | Confirmed
CustomBookmarkUpdate (response) | Uses original action unless CustomBookmarkRead is called | Uses original action unless CustomBookmarkRead is called
DatabaseRead  (Browse My Server) | N/A | N/A (Does not use the expansion logic)
GenesisInstall | N/A | N/A (GenesisRead is called first)
GenesisRead (Installed Apps) | Still using old button logic | Still using old button logic

I don't care too much about the CustomBookmarkUpdate case, unless it indicates a bigger problem.  We can discuss tomorrow whether Installed Apps should use the updated button code.

**Comment by JoelProminic** [comment]
From our discussion today, we would like to use the new Bookmark design for Installed Applications as well.

**Comment by piotrzarzycki21** [comment]
> From our discussion today, we would like to use the new Bookmark design for Installed Applications as well.
> 
> The Description can be moved from the current location to be next to the button, to match #50 : ![image](https://user-images.githubusercontent.com/24532731/284672371-91cd1507-3d46-4536-8a94-2fe2c8032665.png)

I have changed this in installed application section as well. It's ready for review.

**Comment by JoelProminic** [comment]
I confirmed the Installed App bookmarks were updated, and the Description is displayed as expected.

There is still a minor issue with defaultAction not updating after a Bookmark is updated.   We confirmed yesterday that other properties will be updated using the response from CustomBookmarkUpdate, but not `defaultAction`.

**Comment by piotrzarzycki21** [comment]
> I confirmed the Installed App bookmarks were updated, and the Description is displayed as expected.
> 
> There is still a minor issue with defaultAction not updating after a Bookmark is updated. We confirmed yesterday that other properties will be updated using the response from CustomBookmarkUpdate, but not `defaultAction`.

This should be fixed.

**Comment by JoelProminic** [comment]
I confirmed the defaultAction is updated after a CustomBookmarkUpdate.  I don't think there are any remaining problems for this issue.
