### ISSUE TITLE
Description for Bookmarks

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#50]
We would also like to add an optional description property for the bookmarks, similar to what we have for Installed Applications.  This will need to be updated in the Royale form as well as the database and agents.  The current plan is to display the description to the right of the collapsed  bookmarks.

_Originally posted by @JoelProminic in https://github.com/Moonshine-IDE/Super.Human.Portal/issues/46#issuecomment-1810848496_

I confirmed that the description is displayed to the right of the bookmarks with the update.  However, the form for creating and editing bookmarks is not updated.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have added Description text area to Bookmarks. I have found small bug which is probably on your sigh - when I edit bookmark and add some description to it - updated object do not returns `description` field. Once you fix that issue should be good for close. 

<img width="521" alt="Screenshot 2023-11-24 at 11 17 52" src="https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24554795/b9732ad0-6348-46d1-aaf0-055388b3a4b1">

**Comment by JoelProminic** [comment]
I added `description` to the response for CustomBookmarkUpdate.  I did some tests:

Test | Result
-- | -- 
Create a bookmark with a description | Description is saved and displayed properly.
Update the description for a bookmark | Description is updated in UI and database.  Description returned in update agent output.
Refresh the page and reopen bookmark | Description is displayed
