### ISSUE TITLE
Report FireFox as Recommended Browser

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#55]
We would like to display a message on startup  recommending that users use Firefox for Super.Human.Portal (if they are not already using Firefox).  Some notes:
- Limit how often it is displayed
    - Once per day?  Could be done with expiring cookie
    - Once per tab?  This could be an in-memory solution
- There should be a configuration option to block this check.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have implemented Jewel Snackbar to display message. To test this grab latest build. 

- It displays once when user is logged in - regardless whether it is anonymous user or not.
- Message is displayed until user close it
- Message is displayed once until user clear cookies 

<img width="1778" alt="Screenshot 2024-05-08 at 14 04 33" src="https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24554795/cb80190b-44c1-4d3a-b796-d00a9b00e42f">

**Comment by JoelProminic** [comment]
A small change to the message:

> "It appears you are currently using a browser other than Firefox. For the optimum experience and full compatibility with all the features of our app, we highly recommend using Firefox."

**Comment by piotrzarzycki21** [comment]
Message has been changed.

**Comment by JoelProminic** [comment]
The updated prompt looks like this:
![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/6b83cab6-8806-48d0-ad63-c656d46f0e22)

It looks fine in dark mode as well.
