### ISSUE TITLE
Allow Non-Administrators to View Genesis Applications

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#59]
From @JustinProminic

>I asked Triston to run some tests, and he when using Super.Human.Portal as not an administrator is unable to see the other applications to install.
>
>I think we should allow non-administrators to view, but not install, the applications.

Currently the Genesis Apps and Installed Apps are hidden if the user does not have the Administrator role:

![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/ce5dd61a-b483-4ecf-8030-48559ccb9dd1)

We want to make the applications visible to the other users so that if they see something they need, they can ask an administrator to install it.  For now, I'd like to show them something like this:

![image](https://github.com/Moonshine-IDE/Super.Human.Portal/assets/24532731/3d0d8450-82ac-46a6-9030-30750f11a679)

So, users *without* the Administrator role would be able to see 
- Genesis Apps 
- Installed Apps.

However, these features should only be available if the user has the "Administrator" role.
- Additional directories should be hidden - this is probably not useful for non-Admnistrators unless we want people to be able to add their own Genesis Directories later (this could have separate security implications though).
- The Install button in Genesis Apps should be disabled, and change the text to "Install (Admin-only)"

We discussed changing the Install button to make it send an email to the administrators instead, but this would be a bigger change on the backend.

I will need to update the GenesisRead to allow non-Administrator access, but I ran out of time for this today.   

Note that this is a change to the roles we decided on for #43
https://github.com/Moonshine-IDE/Super.Human.Portal/issues/43#issuecomment-1821821786
https://github.com/Moonshine-IDE/Super.Human.Portal/issues/43#issuecomment-1843595625
https://github.com/Moonshine-IDE/Super.Human.Portal/blob/2f7ede5e98da2ba606115b5bb01c1cd8135392b6/Super.Human.Portal_Agents/src/test/groovy/auth/SimpleRoleSecuritySpec.groovy#L157-L178

**Comment by piotrzarzycki21** [comment]
@JoelProminic this is issue for that quick update. If you won't add details today I will do this tomorrow.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes for this issue. I believe you need remove restriction for retrieving Genesis Apps and Installed application on your sight, because now we are getting error during that operation. Newest build should have my changes.

**Comment by JoelProminic** [comment]
I made an update to the `features/issue_56_tile_view_getting_started` branch (we can cherry pick this to `main` if desired). With the update, this is mostly working.  I see a problems with the Install button, though (which you wouldn't have been able to test).

Feature | Administrator | Not Administrator
-- | -- | --
Genesis Apps | Visible | Visible
Genesis Apps > Additional Directories | Visible | Hidden
Installed Apps | Visible | Visible
Install button | Original label.  BUG:  Install button was enabled even if no app was selected | Visible, label updated.  BUG:  enabled, so we get a permissions error on the agent.

I noticed that the Genesis Apps is not highlighted when it is selected in the sidebar.  This seems to be an existing issue - I suspect this is because it is a category/folder.

**Comment by piotrzarzycki21** [comment]
> Install button	Original label. BUG: Install button was enabled even if no app was selected	Visible, label updated. BUG: enabled, so we get a permissions error on the agent.

I have pushed fix to main and my branch for that part.

**Comment by piotrzarzycki21** [comment]
> I noticed that the Genesis Apps is not highlighted when it is selected in the sidebar. This seems to be an existing issue - I suspect this is because it is a category/folder.

@JoelProminic I have fixed this one as well. It's been pushed to main and to branch with tile view.

**Comment by JoelProminic** [comment]
> I noticed that the Genesis Apps is not highlighted when it is selected in the sidebar. This seems to be an existing issue - I suspect this is because it is a category/folder.

This is no longer triggering with the latest build.

I also confirmed the Install button is hidden and displayed as expected.
