### ISSUE TITLE
Better error handling when the Nomad server is unavailable

### ISSUE THREAD

**Issue by piotrzarzycki21** [Moonshine-IDE/Super.Human.Portal#60]
From Justin's email:

> The nomad server URL was not available due to a DNS problem first, and then later after fixing the DNS issue it continued to not work because Nomad itself was not running, then apparently was running and crashed.
> 
> In all 3 cases, clicking the blue button or grey button did absolutely nothing.
> 
> No UI feedback occurred, and as a user it was very confusing why nothing was happening.
> 
> We need some way to provide UI feedback if there is any exception communicating with or launching Nomad.  It needs to state something like:
> 
> "It looks like the server for <protocol://nomad server url:port> is not responding.  Please check DNS, the Domino server, and the Nomad task to ensure it is running."

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes for this where I'm checking availability of nomad_helper_url if exists. When user click on Open in Nomad and url is not available message suggested by @JustinProminic will be displayed.

**Comment by JoelProminic** [comment]
I ran some tests with [this build](https://github.com/Moonshine-IDE/Super.Human.Portal/actions/runs/10012050778)
1. Open Super.Human.Portal and login
2. Open Installed Apps > Super Human Portal (there are other ways to get to an example link)
3. Click Configuration Database without expanding


Test | Behavior
-- | --
Nomad up and reachable, tab not open| Nomad opens properly
Nomad up and reachable, tab open| Could not test - Nomad was not authenticating for some reason in my test
Break nomadweb DNS lookup with /etc/hosts | BUG:  No error in UI.  Browser debug tools show connection refused, and SHP attempts to open nomadhelper.html URL anyway.
Rename nomadhelper.html | BUG:  No error in UI.  Oddly, console shows a CORS error
CORS error | BUG:  Nothing happens in UI.  I triggered this case by accident when testing the down server

**Comment by piotrzarzycki21** [comment]
Sounds as usual more work to do. Let's see if I will be able to fix that on Monday. 

What do you mean that did you break DNS lookup in /etc/hosts ?

**Comment by JoelProminic** [comment]
To use the /etc/hosts test method:
1. Open the hosts file as an administrator on your local machine (not the SHI instance).  Substitute the editor of your choice.
2. Find the line for your VM.  For example:

```
10.0.14.10       demo demo.startcloud.com console.demo.startcloud.com domino.demo.startcloud.com restapi.demo.startcloud.com demo.demo.startcloud.com nomadweb.demo.startcloud.com #entry requested by Super.Human.Installer on 2023-12-12T18:12:42Z for server id 4882
```

3. Comment out or remove the nomadweb... entry
4. Add a new entry like this:

```
127.0.0.1   nomadweb.demo.startcloud.com
```

5. Save the file
6. Run `ping nomadweb.your.server` and make sure it shows 127.0.0.1
7. You may need to restart your browser before the URLs start failing.  I was seeing some strange behavior with caching for Nomad and nomadhelper.html in Firefox.


To test with the rename method, run these commands on the SHI instance:

    sudo su -
    cd /opt/hcl/domino/notes/latest/linux/nomad-files/
    mv nomadhelper.html nomadhelper-hide.html
    # put the file back when done:
    mv nomadhelper-hide.html nomadhelper.html

**Comment by piotrzarzycki21** [comment]
> Rename nomadhelper.html	BUG: No error in UI. Oddly, console shows a CORS error

Can't reproduce this one. After renaming on server homadhelper.html I got proper info about unavailability of file.

**Comment by piotrzarzycki21** [comment]
@JoelProminic It turns out that [URLLoader](https://github.com/apache/royale-asjs/blob/develop/frameworks/projects/Network/src/main/royale/org/apache/royale/net/URLLoader.as) class from Royale does not handle all errors which may occur during loading. I have switched to different class [URLStream](https://github.com/apache/royale-asjs/blob/develop/frameworks/projects/Network/src/main/royale/org/apache/royale/net/URLStream.as) which handle errors more [broadly](https://github.com/apache/royale-asjs/blob/f547da6cbe62e878b54690995b3e0dce18b31b1f/frameworks/projects/Network/src/main/royale/org/apache/royale/net/URLStream.as#L390). It's ready for tests.

**Comment by JoelProminic** [comment]
This is looking better.  I'm still seeing unexpected CORS errors on the console for the other cases, but the cases seem to be working in general.

![image](https://github.com/user-attachments/assets/4d131849-26de-4047-ad9b-11047eb8eb51)


Test | Behavior
-- | --
Nomad up and reachable, tab not open | Nomad opens properly
Nomad up and reachable, tab open | TODO
Break nomadweb DNS lookup with /etc/hosts | Reports an error message
Rename nomadhelper.html | Reports an error message
CORS error | This is still triggering as part of the above cases, and the error message is showing up as expected

If I don't see any more problems, I'll plan to create a release candidate today.
