### ISSUE TITLE
Missing Scroll for Getting Started Page

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#64]
Now that we added a new category in #62, I found that not all categories are fitting on a single screen with the browser size I use.  In the screenshot below, you can see just a sliver of the seventh category  and there is no scroll:
![image](https://github.com/user-attachments/assets/f4409a80-6d93-409d-847d-ec8d1a828d54)

I'd like to see a scroll added for this.  I remember that we discussed this before in the group meetings, but I don't see a corresponding issue.

For now I assigned this to the v1.2 milestone.  If it is easy to update, we can move it to the v1.1 milestone before the release.  I'm planning to do a release of v1.1 tomorrow.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed fix for this.

**Comment by JoelProminic** [comment]
Thanks for the quick update.  The scroll is working like I expect.  I tested:
- My normal window size as reported above
- A large window size - the scroll disappears if all nodes are visible
- A very window, so that the sidebar is hidden
- The list of articles inside a category - these also update the scroll bar

I'll add this to v1.1 milestone and work on the release.
