### ISSUE TITLE
Hide Additional Interfaces for End Users

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#65]
I had a meeting with the Prominic Support team today to discuss using Super.Human.Portal for bookmarks for a customer.  After some discussion, we decided that we need to simplilfy the UI further for the end users.
- Interfaces to hide
    - Browse Server
- Restrict the documents in these interfaces by role.  "Administrator" entries should be hidden
    - Bookmarks?
    - Getting Started
    - Installed applications
- If the above entries are empty after restrictions, hide them

For the Installed applications, I currently don't have documents for these.  The agent reads the installed applications from %DATADIR%/JavaAddin.  @JustinProminic suggested that this flag could be added to the Genesis configuration.

The current security logic is defined [here](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/43#issuecomment-1821821786).   

Feature | Current Default | Current Admin | Proposed End User
-- | -- | -- | --
Login | Allow | Allow | Allow
View Documentastion (Getting Started) | Allow | Allow | Only non-administrator documents
Install Applications | Hide | Allow | Hide
Add additional Genesis Directories | Hide | Allow | Hide
View installed applications | Allow | Allow | Only non-administrator applications
View/Use Bookmakrs | Allow | Allow | Filter by role?
Create/Edit/Delete Bookmarks | Hide | Allow | Hide
Browse My Server | Allow | Allow | Hide

The new role restrictions will be added in the agents.  There is some UI hide/show logic to add as well, and I'll let @piotrzarzycki21 know when we are ready for this.

I'd like to revisit the role system to see if it can handle this.   I think testing the individual documents will be a change for the agent, but I should have some hooks to support this.
jkk

**Comment by JoelProminic** [comment]
Justin proposed that instead of adding new roles, we should have binary flags like (TODO:  choose better names.  Alternatively, ove this to a separate configuration view so that we can make this more clear?):
- allow_non_admin_access_install_applications
- allow_non_admin_access_view_installed
- allow_non_admin_access_admin_applications  (further filter list of installed applications)
- allow_non_admin_access_browse_server
- allow_non_admin_access_manage_bookmarks
- allow_non_admin_access_admin_documentation

Users would be split into two groups, Administrator users and the rest of the users.   This would avoid needing to define and maintain a group with "End Users" or "Technical Users".   

Maintaining the user lists is a problem because:
- The current role logic doesn't support groups
- Even if it did, we have had a hard time keeping the groups maintained.

Justin also expressed concern about using the Genesis API to determine which applications are "Administrator" applications, since this may not scale well as we add more users.  However, the agents are already calling this API to populate the links for installed applications, so this is not a new problem.   We may want to create a separate issue to discuss scaling for Super.Human.Portal and Genesis.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, for the UI updates, I'm thinking about a solution like this in the JSON, which defines which interfaces would be displayed.  Currently, this is [hard-coded based on the roles](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/43#issuecomment-1828823495).  This will allow me to change the implementation in the future without changing the roles:

```
...
"display":
    "documentation":"true",
    "installApps":"false",
    "genesisDirectory":"false",
    "viewInstalledApps":"true",
    "viewBookmarks":"true",
    "manageBookmarks":"false",
    "browseMyServer":"false",
```

Some thoughts:
- Should these be broken down further? For example, convert manageBookmarks to createBookmarks, deleteBookmarks, editorBookmarks
- Some categories would exclude each other.  For example manageBookmarks doesn't make sense without viewBookmarks

This could be either XMLAuthenticationTest (which currently has the roles) or ConfigRead.  Let me know if you have a prefernce


@piotrzarzycki21, let me know if you have more thoughts about this

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21, for the UI updates, I'm thinking about a solution like this in the JSON, which defines which interfaces would be displayed. Currently, this is [hard-coded based on the roles](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/43#issuecomment-1828823495). This will allow me to change the implementation in the future without changing the roles:
> 
> ```
> ...
> "display":
>     "documentation":"true",
>     "installApps":"false",
>     "genesisDirectory":"false",
>     "viewInstalledApps":"true",
>     "viewBookmarks":"true",
>     "manageBookmarks":"false",
>     "browseMyServer":"false",
> ```
> 
> Some thoughts:
> 
> * Should these be broken down further? For example, convert manageBookmarks to createBookmarks, deleteBookmarks, editorBookmarks
> * Some categories would exclude each other.  For example manageBookmarks doesn't make sense without viewBookmarks
> 
> This could be either XMLAuthenticationTest (which currently has the roles) or ConfigRead. Let me know if you have a prefernce
> 
> @piotrzarzycki21, let me know if you have more thoughts about this

I don't remember out of how I'm getting roles, let's have this one added in the same place where I'm getting information about my roles.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, I made an initial update to the agent to allow you to test.  
Branch:  features/issue_65_end_users

I updated the XMLAuthenticationTest agent:   https://domino.myserver.shi.com/SuperHumanPortal.nsf/XMLAuthenticationTest?OpenAgent

```
{
  "roles": [],
  "display": {
    "viewInstalledApps": true,
    "installApps": false,
    "manageBookmarks": false,
    "documentation": true,
    "viewBookmarks": true,
    "browseMyServer": false,
    "additionalGenesis": false
  },
  "errorMessage": "",
  "state": "anonymous",
  "common_name": "Anonymous",
  "username": "Anonymous",
  "status": "anonymous"
}
```

To clarify what each of these mean:

Key |  Interface
-- | --
viewInstalledApps | Installed Apps
installApps | Genesis Directory
manageBookmarks | Add/Edit/Delete in Bookmarks
documentation | Getting Started
viewBookmarks | Bookmarks
browseMyServer | Bookmarks/Browse My Server
additionalGenesis | Genesis Directory/Additional

I'll send you a test database by email.  You will need to deploy it to your SHI instance.  For now, you can manipulate the value using these configuration documents.  I will start working on a proper implementation for this, but this should make testing easy:
![image](https://github.com/user-attachments/assets/6bca37ba-aba0-45f5-9c03-e8ea2a9d2382)

**Comment by JoelProminic** [comment]
Sorry, I see I forgot to push my branch yesterday.  This has been pushed, along with some additional changes that I will write up later.

@piotrzarzycki21, you shouldn't need to deploy the agents - just use the test database I sent yesterday.  I'll let you know if my updates are ready to test, but you will probably find it simpler to update the display options with the current logic.

**Comment by JoelProminic** [comment]
After some thinking, I found a role-based solution that should be straightforward and intuitive.  I don't think it is significantly more complicated that the [solution](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/65#issuecomment-2463458750) that @JustinProminic suggested, and it has more intuitive names for the configuration documents.

I definied RoleRestrictionIDs in the code.  These roughly correspond to to the `display` entries I added yesterday, but note that `documentation` has beens split into `viewDocumentation` and `manageDocumentation`.   I preservied `documentation` in XMLAuthenticationTest for now:

```
	public static final String RESTRICT_DOCUMENTATION_VIEW = "viewDocumentation";
	public static final String RESTRICT_DOCUMENTATION_MANAGE = "manageDocumentation";
	public static final String RESTRICT_APPS_VIEW = "viewInstalledApps";
	public static final String RESTRICT_APPS_INSTALL = "installApps";
	public static final String RESTRICT_BOOKMARKS_VIEW = "viewBookmarks";
	public static final String RESTRICT_BOOKMARKS_MANAGE = "manageBookmarks";
	public static final String RESTRICT_BROWSE_MY_SERVER = "browseMyServer";
	public static final String RESTRICT_GENESIS_MANAGE = "additionalGenesis";
```

Each agent is assigned one of these IDs.  ConfigRead and XMLAuthenticationTest are allowed for All users by default:

```
        agent                               | roleRestrictionID
        new ConfigRead()                    | null
        new XMLAuthenticationTest()         | null
        new DocumentationFormRead()         | SecurityBuilder.RESTRICT_DOCUMENTATION_VIEW
        new DocumentationFormDelete()       | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new DocumentationFormCreate()       | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new DocumentationFormUpdate()       | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new CategoryRead()                  | SecurityBuilder.RESTRICT_DOCUMENTATION_VIEW
        new CategoryDelete()                | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new CategoryCreate()                | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new CategoryUpdate()                | SecurityBuilder.RESTRICT_DOCUMENTATION_MANAGE
        new CustomBookmarkDelete()          | SecurityBuilder.RESTRICT_BOOKMARKS_MANAGE
        new CustomBookmarkCreate()          | SecurityBuilder.RESTRICT_BOOKMARKS_MANAGE
        new CustomBookmarkUpdate()          | SecurityBuilder.RESTRICT_BOOKMARKS_MANAGE
        new CustomBookmarkRead()            | SecurityBuilder.RESTRICT_BOOKMARKS_VIEW
        new DatabaseRead()                  | SecurityBuilder.RESTRICT_BROWSE_MY_SERVER
        new GenesisDirectoryUpdate()        | SecurityBuilder.RESTRICT_GENESIS_MANAGE
        new GenesisDirectoryCreate()        | SecurityBuilder.RESTRICT_GENESIS_MANAGE
        new GenesisDirectoryDelete()        | SecurityBuilder.RESTRICT_GENESIS_MANAGE
        new GenesisDirectoryRead()          | SecurityBuilder.RESTRICT_GENESIS_MANAGE
        new GenesisRead()                   | SecurityBuilder.RESTRICT_APPS_VIEW
        new GenesisInstall()                | SecurityBuilder.RESTRICT_APPS_INSTALL



	}
```

And then each ID has a corresponding configuration document that indicates which roles are allowed for each agent/view.  A configuration like what we discussed for End Users would look like this:
![image](https://github.com/user-attachments/assets/41aab6e8-7c46-4e32-b2fe-0bac7406292b)


This allows fine-tuned control for the different views in Super.Human.Portal. I could even add additional roles without changing the agent or Royale logic.

TODO:
- My logic needs more testing, but the initial behavior looks promising
- I also need a solution to filter individual documentation, bookmarks(?), and Genesis applications by role.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed first changes where I'm using properties from "display" to hide Installed Apps and Bookmarks. However I would like to confirm if actually logic for hiding Bookmarks exists ? 
I should only restrict ability to Add/Edit/Delete for non admin user ? 

I will work on farther restricting.

**Comment by JoelProminic** [comment]
Some more tests on my side, tested against XMLAuthenticationTest:

User Roles | Category Roles | Category Result | Test
-- | -- | -- | --
Anonymous | All | true | Confirm
Anonymous | Anonymous | true | Confirm
Anonymous | NotAnonymous | False | Confirm
Anonymous | Administrator | False | Confirm
Anonymous | Custom | False | Confirm
Anonymous | Administrator, Custom | False | Confirm
NotAnonymous | All | true | Confirm
NotAnonymous | Anonymous | false | Confirm
NotAnonymous | NotAnonymous | true | Confirm
NotAnonymous | Administrator | False | Confirm
NotAnonymous | Custom | False | Confirm
NotAnonymous | Administrator, Custom | False | 
NotAnonymous,Administrator | All | true | Confirm
NotAnonymous,Administrator | Anonymous | false | Confirm
NotAnonymous,Administrator | NotAnonymous | true | Confirm
NotAnonymous,Administrator | Administrator | true | Confirm
NotAnonymous,Administrator | Custom | False | Confirm
NotAnonymous,Administrator | Administrator, Custom | true | Confirm
NotAnonymous,Custom | All | true | Confirm
NotAnonymous,Custom | Anonymous | false | Confirm
NotAnonymous,Custom | NotAnonymous | true | Confirm
NotAnonymous,Custom | Administrator | false | Confirm
NotAnonymous,Custom | Custom | true | Confirm
NotAnonymous,Custom | Administrator, Custom | true | Confirm
NotAnonymous,Administrator,Custom | All | true | Confirm
NotAnonymous,Administrator,Custom | Anonymous | false | Confirm
NotAnonymous,Administrator,Custom | NotAnonymous | true | Confirm
NotAnonymous,Administrator,Custom | Administrator | true | Confirm
NotAnonymous,Administrator,Custom | Custom | true | Confirm
NotAnonymous,Administrator,Custom | Administrator, Custom | true | Confirm

**Comment by piotrzarzycki21** [comment]
@JoelProminic I'm sorry but I have read this again, I thought I understand this logic, yesterday but I'm not.

Let's say that manageBookmarks property is implemented and used on Royale side to hide/show buttons like Add/Edit for Bookmarks. Please provide me steps which allows me to tests that logic. - I would like to modify configuration in the same way as end user is going to do that as an Admin.

**Comment by JoelProminic** [comment]
I sent a database with the role logic.  To test manageBookmarks:
1. Create/update allow_role_manageBookmarks
2. Create/update role_Administrator_users so that Demo Admin is included
3. Login to Super.Human.Portal
4. Check Bookmark buttons.  They should be enabled
5. Create/update role_Administrator_users and remove Demo Admin
6. Refresh Super.Human.Portal
7. Check Bookmark buttons.  They should be disabled/hidden (match the current logic)

**Comment by piotrzarzycki21** [comment]
@JoelProminic I think if someone have insufficient access I should get errorMessage. All our data retrieving is based on that. Some screenshot: 

<img width="1503" alt="Screenshot 2024-11-15 at 09 42 38" src="https://github.com/user-attachments/assets/e02298e2-a33c-48b3-b3d1-19b4ff44302e">

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed code where manageBookmarks seems to be working correctly. I'm switching visibility of buttons based on property `manageBookmarks` which seems to be switching true/false when I do your [scenario](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/65#issuecomment-2477268711).

Now I would like to focus on Install Apps - Without changing my code if I set to empty Configuration field: **allow_roles_installApps** - Next I do `GenesisRead?OpenAgent` I will get empty errorMessage (which should be change in my opinion), some state (example is on screenshot) - In UI I'm not displaying anything. 

Please describe for me how should behave UI when I click Genesis Apps ? 
What property should I use to change visibility of some UI elements for that category ? 
Not there is button "Install (Admin-only)" which is disabled based on [roles](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/e96902d59baabbf5f6ab04eed269e0b4d9aad70b/Super.Human.Portal_Royale/src/net/apacheRoyaleTemplatedApp/mediator/applications/MediatorGenesisApps.as#L113).

**Comment by JoelProminic** [comment]
The meetings ran late, and the agent updates will take a while, so you don't need to wait up on for me today, @piotrzarzycki21 .   Let me know if you have any thoughts on my notes above, though.

**Comment by piotrzarzycki21** [comment]
Thanks Joel. Can't progress more on this today. I will look into that on Sunday.

**Comment by JoelProminic** [comment]
After reviewing GensisRead, I see that it has a single list of apps, so I can't easily separate out the data for "Installed Apps" and "Genesis Apps".   So, I decided that `viewInstalledApps` should hide both "Installed Apps" and "Genesis Apps".  We may revisit this later, if needed.

Otherwise, I have a working implementation of the document filter.  I have tested this with the Documentation view, and it is working as expected.  I added the new field for these Forms (but I have not tested the other forms yet):
- Documentation Form
- Category - this would be a little finicky, but it will let us avoid having an empty category after Documentation Form updates
- CustomBookmark
- GensisDirectory

My TODO:
- more testing
- Filter apps by local txt file or JSON flag

I sent an updated copy of the database by email for testing.  I updated the documenation on the `allow_roles_` documents in preparation for production - these may be helpful for clarifying the logic.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have pushed changes where I'm hiding/showing UI elements based on this [write up](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/65#issuecomment-2469313796), I get into account as well [this](https://github.com/Moonshine-IDE/Super.Human.Portal/issues/65#issuecomment-2480190713). Please test and let me know if it's working. I need to restrict getting data separately, but first I would like to know if UI elements are working. I was trying to figure out how to test this on my own, but I'm still confused.

**Comment by JoelProminic** [comment]
I ran a test with the default configuration:
![image](https://github.com/user-attachments/assets/17892863-0a68-4b79-ad5a-06f15b24741f)

With `role_Administrator_users=Demo Admin`, was able to see all interfaces.   If I removed the Demo Admin user, then only Getting Started and Bookmarks were availabe, but I got thie error for the GenesisRead agent.  This agent should not be called if `viewInstalledApps==false`.   Is there some other feature that still requires this?
![image](https://github.com/user-attachments/assets/ba3ccecb-2ec2-480c-abac-6a3374ff383b)

**Comment by piotrzarzycki21** [comment]
It looks like it's working correctly, so I need to just restrict retrieving data from the backend based on properties.

**Comment by JoelProminic** [comment]
I did some more testing, and found some more problems:

display property | Behavior
-- | --
viewInstalledApps | BUG:  GenesisRead triggers error when this is false (this is the error from above)
viewDocumentation | BUG:  Not hidden, but no documents
installApps | BUG:  ignored.  Is this based on the Administrator role instead, still?
additionalGenesis | Works
manageBookmarks | BUG:  ignored.  Is this based on the Administrator role instead, still?
viewBookmarks | Not expected to work current.  BUG:  no authentication error on CustomBookmarksRead agent, but there was an error on GenesisRead. This seems to be a bug on my side.
browseMyServer | Works
manageDocumentation | BUG:  does not work.  Is this based on ui_documentation_editable instead?

**Comment by piotrzarzycki21** [comment]
@JoelProminic manageDocumentation depends on [both properties](https://github.com/Moonshine-IDE/Super.Human.Portal/blob/1906af1a9468e268ea7b580c653c3db312850e45/Super.Human.Portal_Royale/src/generated/Super.Human.Portal_Royale/views/modules/DocumentationForm/DocumentationFormServices/DocumentationFormProxy.as#L527)

**Comment by piotrzarzycki21** [comment]
> I did some more testing, and found some more problems:
> 
> display property	Behavior
> viewInstalledApps	BUG: GenesisRead triggers error when this is false (this is the error from above)
> viewDocumentation	BUG: Not hidden, but no documents
> installApps	BUG: ignored. Is this based on the Administrator role instead, still?
> additionalGenesis	Works
> manageBookmarks	BUG: ignored. Is this based on the Administrator role instead, still?
> viewBookmarks	Not expected to work current. BUG: no authentication error on CustomBookmarksRead agent, but there was an error on GenesisRead. This seems to be a bug on my side.
> browseMyServer	Works
> manageDocumentation	BUG: does not work. Is this based on ui_documentation_editable instead?

@JoelProminic Issues should ba addressed. However I'm not sure how to behave in case of Hidden Getting Started. Test and see how it looks like currently when viewDocumentation is false.

**Comment by JoelProminic** [comment]
@piotrzarzycki21, the updates look mostly good:

display property | Behavior
-- | --
viewInstalledApps | Hidden, no errors
viewDocumentation | Hidden in sidebar.  BUG:   Bookmarks > Default should be the landing page in this case
installApps | 
additionalGenesis | Works
manageBookmarks | Enables Add Bookmark in Bookmarks > Default.  BUG:  Does not allow adding bookmarks from Browse My Server.  This seems to be based on the Administrator role still
viewBookmarks | Not expected to work currently.  NOTE: the agent discrepancies I reported yesterday seem to be some caching in the developer console.
browseMyServer | Works
manageDocumentation | Works

You can test disabling viewDocumentation like this:
![image](https://github.com/user-attachments/assets/3eb66ac4-7700-4e6e-8f61-7a4441516761)


Currently I see this.  Getting Started is hidden in the sidebar, but we would need a replacement home page.  I suggested Bookmarks > Default, but would it be better to have a generic home page instead?  We should go with a simple solution for this for now.
![image](https://github.com/user-attachments/assets/855a8fd4-dc6e-4e38-8d47-a4d427fbfe3e)

**Comment by JoelProminic** [comment]
I have an implementation for allowedRoles on the Genesis applications.  

@dpastov, here are the rules I used.  The Genesis side doesn't have to be implemented immediately, but let me know if you need any changes before i push out Super.Human.Portal.
- Global roles:  From the application JSON, I read the `allowedRoles` property.  This is expected to be an array of strings, but a single string value is also supported.  I am open to other names or casing if that will fit better with your API.
- Local override:  I read JavaAddins/appID/config.txt and look for the `allowedRoles` property.  This is expected to be a comma-separated string.   Is it safe to use `config.txt` for this, or should we use a sparate file?
- If allowedRoles is defined in both locations, config.txt has priority. 
- If allowedRoles is empty or not defined in both locations, then allow access for all roles (still restricted by agent access rules)
- If the `filter_documents_by_role` configuration document is set to "false" in SuperHumanPortal.nsf, the defined `allowedRoles` will be ignored.
- For now, the only shared role is "Administrator".  We can discuss adding additional roles that may be defined in Genesis.

I haven't tested the JSON logic yet.  @JustinProminic and I discussed setting up a local cache of the JSON, so I may procesed with that and use it for testing. 

My tests with config.txt

allowedRoles | User is Administrator | filter_documents_by_role | Application returned
-- | -- | -- | --
Missing | No | true | yes
Empty | No | true | yes
Administrator | No | true | no
Administrator | Yes | true | Yes
Administrator | No | false | no

**Comment by piotrzarzycki21** [comment]
> manageBookmarks	Enables Add Bookmark in Bookmarks > Default. BUG: Does not allow adding bookmarks from Browse My Server. This seems to be based on the Administrator role still

@JoelProminic It is not based on Roles anymore. I just checked it. However during the tests I have found scenario where there was NPE - I have fixed it. Maybe this influence some errors and logic wasn't working correctly. You can try newest build.

**Comment by JoelProminic** [comment]
If viewDocumentation==false, show a landing page with this message:

> Welcome to Super.Human.Portal.  Select an option from the sidebar.

Linking to Bookmarks > Default would be difficult, so I don't want to spend more time on this for a case we probably won't use.

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have added text when there is no data. It's not ideal, I think separate issue to improve that maybe required, but let's see.

**Comment by JoelProminic** [comment]
@piotrzarzycki21's updates look good.  This message is sufficient for now:
![image](https://github.com/user-attachments/assets/a8c980f2-7550-418b-8865-8ca06aa45e38)

And I confirmed that I can add bookmarks from the Browse My Server interface when manageBookmarks==true.

I will merge this branch and start working on a release.
