### ISSUE TITLE
No Error Message for Invalid Password

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#74]
While using the 1.2.0 release build, I noticed that I am not getting error messages in the login prompt when I enter an invalid password.  I see something happen when I click the button, but it just returns to the prompt:
![image](https://github.com/user-attachments/assets/c57493e1-0273-428e-a06d-ccfcec0549fd)

**Comment by piotrzarzycki21** [comment]
@JoelProminic I have fixed this error. It may occurs in MyAccount as well, so I raised issue there to observer this area.

**Comment by JoelProminic** [comment]
This looks good with the update.  I couldn't trigger a problem with my initial tests, but I may try some more ideas later.
