### ISSUE TITLE
Improve Header Appearance

### ISSUE THREAD

**Issue by JoelProminic** [Moonshine-IDE/Super.Human.Portal#9]
The header for Documentation form is supposed to display the the DocumentationName and Documentation UNID like this:

> DocumentationName (DocumentationUNID)
> Genesis.Directory for discovering new Domino applications (1)

Currently it looks like this:
![image](https://user-images.githubusercontent.com/24532731/214371438-0c6ada26-315e-4633-893d-3769d6c79e10.png)
![image](https://user-images.githubusercontent.com/24532731/214371314-51d178e5-cc9a-4d3b-b99f-831158e813da.png)

We need to shrink the DocumentationUNID field and let the DocumentationName expand so that it is more visible.  

This header should also be larger.

**Comment by piotrzarzycki21** [comment]
@JoelProminic Take a look into improvements. In non edit mode labels are being stretched to the size of text. In edit mode I have change TextInput to TextArea for description (DocumentationName) and left as TextInput DocumentationUNID. If that looks weird maybe it should be displayed vertically.

**Comment by piotrzarzycki21** [comment]
Wider description
shorter UNID
Add label to shorter UNID

**Comment by piotrzarzycki21** [comment]
> Wider description shorter UNID Add label to shorter UNID

I have made following improvements. Everything is on the branch related to #10

**Comment by piotrzarzycki21** [comment]
Merged to main.
